language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "pypy"
env:
  global:
      - PATH="/usr/lib/ccache:$PATH"

notifications:
  email:
    - emmett@parsely.com

install:
    - |
        if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
          export PYENV_ROOT="$HOME/.pyenv"
          if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
            pushd "$PYENV_ROOT" && git pull && popd
          else
            rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
          fi
          export PYPY_VERSION="4.0.1"
          "$PYENV_ROOT/bin/pyenv" install --skip-existing "pypy-$PYPY_VERSION"
          virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
          source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
        fi
    - pip install -U pip setuptools
    - pip install tox tox-travis

script:
    - tox

branches:
  only:
    - master
